### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters

### ISSUE THREAD

**Issue by jacopomarcovaldi** [vikstrous/pirate-get#101]
Hi, here you can find the full error log:

Traceback (most recent call last):                                                                                                                                                                            
  File "/usr/local/bin/pirate-get", line 9, in <module>                                                                                                                                                       
    load_entry_point('pirate-get==0.2.10', 'console_scripts', 'pirate-get')()                                                                                                                                 
  File "/usr/local/lib/python3.4/dist-packages/pirate/pirate.py", line 424, in main                                                                                                                           
    pirate_main(args)                                                                                                                                                                                         
  File "/usr/local/lib/python3.4/dist-packages/pirate/pirate.py", line 338, in pirate_main                                                                                                                    
    printer.search_results(results, local=args.source == 'local_tpb')                                                                                                                                         
  File "/usr/local/lib/python3.4/dist-packages/pirate/print.py", line 98, in search_results                                                                                                                   
    self.print(table)                                                                                                                                                                                         
  File "/usr/local/lib/python3.4/dist-packages/pirate/print.py", line 37, in print                                                                                                                            
    return builtins.print(*args, **kwargs)                                                                                                                                                                    
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 1869-1870: ordinal not in range(256)

Can you help me? Thank you.

**Comment by rnhmjoj** [comment]
You should change your terminal emulator text encoding to Unicode.
Try setting one of these variables
```sh
export LANG=en_US-UTF-8
export PYTHONIOENCODING=utf-8
```

**Comment by jacopomarcovaldi** [comment]
I am sorry but i am not so cofident with raspbian  and system variables.
I executed export LANG=en_US-UTF-8 and export PYTHONIOENCODING=utf-8 and now i read this error:
Traceback (most recent call last):                                                                                                                                                                            
  File "/usr/local/bin/pirate-get", line 10, in <module>                                                                                                                                                      
    load_entry_point('pirate-get==0.2.10', 'console_scripts', 'pirate-get')()                                                                                                                                 
  File "/usr/local/lib/python3.4/dist-packages/pirate/pirate.py", line 424, in main                                                                                                                           
    pirate_main(args)                                                                                                                                                                                         
  File "/usr/local/lib/python3.4/dist-packages/pirate/pirate.py", line 338, in pirate_main                                                                                                                    
    printer.search_results(results, local=args.source == 'local_tpb')                                                                                                                                         
  File "/usr/local/lib/python3.4/dist-packages/pirate/print.py", line 98, in search_results                                                                                                                   
    self.print(table)                                                                                                                                                                                         
  File "/usr/local/lib/python3.4/dist-packages/pirate/print.py", line 37, in print                                                                                                                            
    return builtins.print(*args, **kwargs)                                                                                                                                                                    
UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 161: ordinal not in range(128) 

Now is ASCII :D 

Can you help me :) 

Thank you :)

**Comment by rnhmjoj** [comment]
Uhm, what's the output of `locale`? Also what terminal are you using?

**Comment by jacopomarcovaldi** [comment]
I type sudo raspi-conf command and i set only it_IT-UTF8 (and not it and en) and now it's working.
Thank you.
