### ISSUE TITLE
issues with latest install on mac

### ISSUE THREAD

**Issue by BardiaAfshin** [vikstrous/pirate-get#109]
reproduce:
```bash
pirate-get 'testing'
```
```python
Trying http://tbmirror.us... Failed 
Trying http://proxyspotting.in... Traceback (most recent call last):
  File "/usr/local/bin/pirate-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/pirate/pirate.py", line 425, in main
    pirate_main(args)
  File "/usr/local/lib/python3.5/site-packages/pirate/pirate.py", line 328, in pirate_main
    results, site = search_mirrors(printer, args)
  File "/usr/local/lib/python3.5/site-packages/pirate/pirate.py", line 260, in search_mirrors
    result = connect_mirror(mirror, printer, args)
  File "/usr/local/lib/python3.5/site-packages/pirate/pirate.py", line 248, in connect_mirror
    mirror=mirror)
  File "/usr/local/lib/python3.5/site-packages/pirate/torrent.py", line 147, in remote
    res_l += parse_page(res)
  File "/usr/local/lib/python3.5/site-packages/pirate/torrent.py", line 106, in parse_page
    tag['href'].startswith('magnet'))['href']
TypeError: 'NoneType' object is not subscriptable
```

Tested this with a custom configuration following the instructions on the github repo and without custom configuration.

**Comment by rnhmjoj** [comment]
Thank you for reporting it: this is one of the few mirrors that don't have magnets in the search results.
I have updated the blacklist with it. Meanwhile, If you are still hitting it, you should find a working mirror and set it as default. Use the `--mirror` option or set it in the config file.
